import { Tool, Category } from '../types/database';

export const LOCAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Video Editing', slug: 'video-editing', icon: 'Video', description: 'Create and edit stunning videos with AI power.' },
  { id: '2', name: 'Image Generation', slug: 'image-generation', icon: 'ImageIcon', description: 'Transform text into beautiful images and art.' },
  { id: '3', name: 'Text & Writing', slug: 'text-writing', icon: 'Type', description: 'Write blogs, emails, and code with AI assistance.' },
  { id: '4', name: 'Coding Assistants', slug: 'coding-assistants', icon: 'Code', description: 'Supercharge your development workflow.' },
  { id: '5', name: 'Audio & Music', slug: 'audio-music', icon: 'Music', description: 'Generate music and realistic voiceovers.' },
  { id: '6', name: 'Productivity', slug: 'productivity', icon: 'Zap', description: 'Automate tasks and get more done in less time.' },
  { id: '7', name: 'Search & Research', slug: 'search-research', icon: 'Search', description: 'Find information and cite sources accurately.' },
  { id: '8', name: 'Marketing & SEO', slug: 'marketing-seo', icon: 'TrendingUp', description: 'Grow your business with AI-driven insights.' },
  { id: '9', name: 'Customer Support', slug: 'customer-support', icon: 'MessageSquare', description: 'Provide instant, intelligent support to users.' },
  { id: '10', name: 'Design', slug: 'design', icon: 'Palette', description: 'AI tools for UI/UX and graphic designers.' },
  { id: '11', name: 'Education', slug: 'education', icon: 'GraduationCap', description: 'Learn new skills and study smarter with AI.' },
  { id: '12', name: 'Finance', slug: 'finance', icon: 'Briefcase', description: 'Analyze markets and manage your money.' },
  { id: '13', name: 'Healthcare', slug: 'healthcare', icon: 'HeartPulse', description: 'AI assistants for health and wellness.' },
  { id: '14', name: 'Legal', slug: 'legal', icon: 'Scale', description: 'Draft contracts and research case law.' },
  { id: '15', name: 'HR & Recruitment', slug: 'hr', icon: 'Users', description: 'Find and hire the best talent with AI.' },
  { id: '16', name: 'Data & Analytics', slug: 'data', icon: 'BarChart3', description: 'Turn data into actionable insights.' }
];

export const LOCAL_TOOLS: Tool[] = [
  // Video
  { id: 'v1', view_count: 850, use_cases: ['Content Creation', 'Social Media'], name: 'Invideo AI', description: 'Turn text into video instantly with AI-generated scripts and footage.', url: 'https://invideo.io', pricing: 'Freemium', category_slug: 'video-editing', rating: 4.8, tags: ['Trending', 'Easy to Use'] },
  { id: 'v2', view_count: 920, use_cases: ['Filmmaking', 'VFX'], name: 'Runway Gen-2', description: 'Advanced generative AI for video creation and editing.', url: 'https://runwayml.com', pricing: 'Paid', category_slug: 'video-editing', rating: 4.9, tags: ['Professional', 'Advanced'] },
  { id: 'v3', view_count: 1200, use_cases: ['Cinematography', 'Animation'], name: 'Sora', description: 'OpenAI’s text-to-video AI model generating highly realistic scenes.', url: 'https://openai.com/sora', pricing: 'Paid', category_slug: 'video-editing', rating: 5.0, tags: ['Cutting-Edge', 'Realistic'] },
  { id: 'v4', view_count: 650, use_cases: ['Training Videos', 'Marketing'], name: 'Synthesia', description: 'Create professional AI videos from text with synthetic avatars.', url: 'https://synthesia.io', pricing: 'Paid', category_slug: 'video-editing', rating: 4.7, tags: ['Business', 'Avatars'] },
  { id: 'v5', view_count: 3000, use_cases: ['TikTok', 'Reels'], name: 'CapCut', description: 'A versatile video editor now supercharged with AI captioning and effects.', url: 'https://capcut.com', pricing: 'Free', category_slug: 'video-editing', rating: 4.9, tags: ['Free', 'Social Media', 'Hot'] },
  { id: 'v6', view_count: 540, use_cases: ['Subtitling', 'Podcasts'], name: 'Veed.io', description: 'Online AI video editor with auto-subtitles and translater.', url: 'https://veed.io', pricing: 'Freemium', category_slug: 'video-editing', rating: 4.6, tags: ['Subtitles', 'Online'] },
  { id: 'v7', view_count: 780, use_cases: ['Audio Editing', 'Transcription'], name: 'Descript', description: 'Audio and video editing as easy as editing a doc.', url: 'https://descript.com', pricing: 'Freemium', category_slug: 'video-editing', rating: 4.8, tags: ['Innovative', 'Podcasting'] },
  { id: 'v8', view_count: 420, use_cases: ['Shorts creation', 'Highlights'], name: 'Opus Clip', description: 'AI video clipping tool that turns long videos into viral shorts.', url: 'https://opus.pro', pricing: 'Freemium', category_slug: 'video-editing', rating: 4.7, tags: ['Shorts', 'Automation'] },
  { id: 'v9', view_count: 310, use_cases: ['Prototyping', 'Art'], name: 'Pika Labs', description: 'An idea-to-video platform that brings your creativity to life.', url: 'https://pika.art', pricing: 'Free', category_slug: 'video-editing', rating: 4.5, tags: ['Creative', 'Beta'] },
  { id: 'v10', view_count: 290, use_cases: ['Explainer Videos', 'Sales'], name: 'HeyGen', description: 'AI video generation platform for engaging business videos with avatars.', url: 'https://heygen.com', pricing: 'Paid', category_slug: 'video-editing', rating: 4.8, tags: ['Marketing', 'High Quality'] },

  // Image
  { id: 'i1', view_count: 2400, use_cases: ['Concept Art', 'Design'], name: 'Midjourney', description: 'High-quality AI image generation accessible via Discord.', url: 'https://midjourney.com', pricing: 'Paid', category_slug: 'image-generation', rating: 4.9, tags: ['Best Quality', 'Artistic'] },
  { id: 'i2', view_count: 2100, use_cases: ['Illustrations', 'Stock Photos'], name: 'DALL-E 3', description: 'OpenAI’s powerful image generator that seamlessly understands intricate prompts.', url: 'https://openai.com/dall-e-3', pricing: 'Paid', category_slug: 'image-generation', rating: 4.8, tags: ['Easy Prompts', 'Versatile'] },
  { id: 'i3', view_count: 1800, use_cases: ['Open Source', 'Custom Models'], name: 'Stable Diffusion', description: 'Open-source deep learning model for text-to-image generation.', url: 'https://stability.ai', pricing: 'Free', category_slug: 'image-generation', rating: 4.7, tags: ['Open Source', 'Customizable'] },
  { id: 'i4', view_count: 950, use_cases: ['Game Assets', 'Concept Art'], name: 'Leonardo.ai', description: 'Generate production-quality assets for your creative projects.', url: 'https://leonardo.ai', pricing: 'Freemium', category_slug: 'image-generation', rating: 4.8, tags: ['Asset Gen', 'Beautiful UI'] },
  { id: 'i5', view_count: 1400, use_cases: ['Photo Editing', 'Graphic Design'], name: 'Adobe Firefly', description: 'Generative AI made for creators inside Adobe applications.', url: 'https://adobe.com/firefly', pricing: 'Paid', category_slug: 'image-generation', rating: 4.7, tags: ['Adobe Sync', 'Clean'] },
  { id: 'i6', view_count: 1700, use_cases: ['Social Media', 'Presentations'], name: 'Canva Magic Studio', description: 'All the power of AI integrated directly into Canva designs.', url: 'https://canva.com', pricing: 'Freemium', category_slug: 'image-generation', rating: 4.9, tags: ['Design for All', 'Fast'] },
  { id: 'i7', view_count: 820, use_cases: ['Typography', 'Logos'], name: 'Ideogram', description: 'AI image generator focusing on highly accurate text rendering in images.', url: 'https://ideogram.ai', pricing: 'Free', category_slug: 'image-generation', rating: 4.8, tags: ['Typography', 'Text Focus'] },
  { id: 'i8', view_count: 640, use_cases: ['E-commerce', 'Product Shots'], name: 'Photoroom', description: 'Create professional images and remove backgrounds instantly.', url: 'https://photoroom.com', pricing: 'Freemium', category_slug: 'image-generation', rating: 4.7, tags: ['E-commerce', 'Background Removal'] },

  // Text
  { id: 't1', view_count: 9900, use_cases: ['Chatbot', 'Brainstorming'], name: 'ChatGPT', description: 'The wildly popular conversational AI standard from OpenAI.', url: 'https://chatgpt.com', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.9, tags: ['Most Popular', 'Versatile'] },
  { id: 't2', view_count: 3200, use_cases: ['Long-form Writing', 'Coding'], name: 'Claude 3', description: 'Anthropic’s powerful, human-like AI assistant for writing and analysis.', url: 'https://anthropic.com/claude', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.8, tags: ['Smart', 'Nuanced'] },
  { id: 't3', view_count: 2800, use_cases: ['Research', 'Integration'], name: 'Gemini', description: 'Google’s multimodal AI model that excels at reasoning and coding.', url: 'https://gemini.google.com', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.7, tags: ['Google Native', 'Multimodal'] },
  { id: 't4', view_count: 2100, use_cases: ['Fact Checking', 'Citations'], name: 'Perplexity AI', description: 'An AI-powered search engine that answers questions with citations.', url: 'https://perplexity.ai', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.9, tags: ['Research', 'Accurate'] },
  { id: 't5', view_count: 890, use_cases: ['Copywriting', 'Ad Copy'], name: 'Copy.ai', description: 'AI powered copywriter that generates high-quality marketing text.', url: 'https://copy.ai', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.6, tags: ['Marketing', 'Fast'] },
  { id: 't6', view_count: 1100, use_cases: ['Marketing', 'Blogs'], name: 'Jasper AI', description: 'An AI copilot for enterprise marketing teams and content creators.', url: 'https://jasper.ai', pricing: 'Paid', category_slug: 'text-writing', rating: 4.7, tags: ['Enterprise', 'Content'] },
  { id: 't7', view_count: 3400, use_cases: ['Note Taking', 'Wikis'], name: 'Notion AI', description: 'Write, brainstorm, edit, and summarize directly inside your Notion workspace.', url: 'https://notion.so', pricing: 'Paid', category_slug: 'text-writing', rating: 4.8, tags: ['Productivity', 'Integrated'] },
  { id: 't8', view_count: 1500, use_cases: ['Proofreading', 'Tone Parsing'], name: 'GrammarlyGO', description: 'On-demand AI communication assistance inside Grammarly.', url: 'https://grammarly.com', pricing: 'Freemium', category_slug: 'text-writing', rating: 4.7, tags: ['Writing', 'Correction'] },

  // Coding
  { id: 'c1', view_count: 4500, use_cases: ['Code Completion', 'Refactoring'], name: 'GitHub Copilot', description: 'Your AI pair programmer built right into your editor.', url: 'https://github.com/features/copilot', pricing: 'Paid', category_slug: 'coding-assistants', rating: 4.9, tags: ['Essential', 'Developer'] },
  { id: 'c2', view_count: 1800, use_cases: ['IDE', 'Auto-fix'], name: 'Cursor', description: 'The AI-first code editor designed to help you write software faster.', url: 'https://cursor.sh', pricing: 'Freemium', category_slug: 'coding-assistants', rating: 4.9, tags: ['Best IDE', 'Fast'] },
  { id: 'c3', view_count: 980, use_cases: ['Free Completion', 'Chat'], name: 'Codeium', description: 'Free AI code completion and chat tool for developers.', url: 'https://codeium.com', pricing: 'Free', category_slug: 'coding-assistants', rating: 4.7, tags: ['Free', 'Alternative'] },
  { id: 'c4', view_count: 760, use_cases: ['AWS', 'Cloud Development'], name: 'Amazon Q Developer', description: 'Generative AI assistant for software development on AWS.', url: 'https://aws.amazon.com/q/developer/', pricing: 'Freemium', category_slug: 'coding-assistants', rating: 4.5, tags: ['AWS', 'Enterprise'] },
  { id: 'c5', view_count: 1300, use_cases: ['React', 'Generative UI'], name: 'v0 by Vercel', description: 'Generative AI UI tool to create React components from text prompts.', url: 'https://v0.dev', pricing: 'Freemium', category_slug: 'coding-assistants', rating: 4.8, tags: ['Frontend', 'Vercel'] },
  { id: 'c6', view_count: 400, use_cases: ['Privacy', 'Code Chat'], name: 'Tabnine', description: 'AI assistant for software developers that anticipates your code.', url: 'https://tabnine.com', pricing: 'Paid', category_slug: 'coding-assistants', rating: 4.6, tags: ['Privacy', 'AI Chat'] },

  // Audio
  { id: 'a1', view_count: 1900, use_cases: ['Voiceover', 'TTS'], name: 'ElevenLabs', description: 'The most realistic AI voice generator and text to speech software.', url: 'https://elevenlabs.io', pricing: 'Freemium', category_slug: 'audio-music', rating: 4.9, tags: ['Best Voice', 'Realistic'] },
  { id: 'a2', view_count: 1200, use_cases: ['Music Generation', 'Songs'], name: 'Suno', description: 'AI music generation that creates full songs with vocals from a text prompt.', url: 'https://suno.com', pricing: 'Freemium', category_slug: 'audio-music', rating: 4.9, tags: ['Music Gen', 'Mind Blowing'] },
  { id: 'a3', view_count: 650, use_cases: ['Beats', 'Instrumentals'], name: 'Udio', description: 'A powerful AI tool for creating high-quality music tracks instantly.', url: 'https://udio.com', pricing: 'Free', category_slug: 'audio-music', rating: 4.8, tags: ['Music Art', 'High Quality'] },
  { id: 'a4', view_count: 420, use_cases: ['E-learning', 'Presentations'], name: 'Murf.ai', description: 'Versatile AI voice generator for e-learning, presentations, and videos.', url: 'https://murf.ai', pricing: 'Paid', category_slug: 'audio-music', rating: 4.7, tags: ['Voiceover', 'Business'] },
  { id: 'a5', view_count: 2300, use_cases: ['Audio Cleanup', 'Podcasts'], name: 'Adobe Podcast AI', description: 'AI-powered audio recording, editing, and voice enhancement tool.', url: 'https://podcast.adobe.com', pricing: 'Free', category_slug: 'audio-music', rating: 4.8, tags: ['Audio Cleanup', 'Adobe'] },

  // Productivity
  { id: 'p1', view_count: 1100, use_cases: ['Transcription', 'Meeting Notes'], name: 'Otter.ai', description: 'Record and review meetings with an AI meeting assistant.', url: 'https://otter.ai', pricing: 'Freemium', category_slug: 'productivity', rating: 4.7, tags: ['Meetings', 'Transcription'] },
  { id: 'p2', view_count: 3200, use_cases: ['Automation', 'Workflows'], name: 'Zapier', description: 'Automate work using AI across 6000+ app integrations.', url: 'https://zapier.com', pricing: 'Freemium', category_slug: 'productivity', rating: 4.9, tags: ['Automation', 'Workflow'] },
  { id: 'p3', view_count: 670, use_cases: ['Presentations', 'Pitch Decks'], name: 'Tome', description: 'Generative AI tool for crafting presentations and documents.', url: 'https://tome.app', pricing: 'Freemium', category_slug: 'productivity', rating: 4.6, tags: ['Presentation', 'AI Deck'] },
  { id: 'p4', view_count: 850, use_cases: ['Slides', 'Websites'], name: 'Gamma', description: 'A new medium for presenting ideas, powered by AI.', url: 'https://gamma.app', pricing: 'Freemium', category_slug: 'productivity', rating: 4.8, tags: ['Beautiful', 'Fast'] },
  { id: 'p5', view_count: 450, use_cases: ['Meeting Summary', 'Action Items'], name: 'Fireflies.ai', description: 'AI notetaker to transcribe, summarize, and analyze meetings.', url: 'https://fireflies.ai', pricing: 'Paid', category_slug: 'productivity', rating: 4.7, tags: ['Analytics', 'Note-taking'] },
  { id: 'p6', view_count: 980, use_cases: ['Task Management', 'Planning'], name: 'Motion', description: 'AI executive assistant that plans your day and builds your schedule automatically.', url: 'https://usemotion.com', pricing: 'Paid', category_slug: 'productivity', rating: 4.8, tags: ['Calendar', 'AI Planning'] },
  { id: 'p7', view_count: 1150, use_cases: ['Email Management', 'Drafting'], name: 'Superhuman', description: 'Blazing fast AI-powered email inbox designed to save you hours every week.', url: 'https://superhuman.com', pricing: 'Paid', category_slug: 'productivity', rating: 4.9, tags: ['Email', 'Premium'] },
  { id: 'p8', view_count: 540, use_cases: ['Slides', 'Presentations'], name: 'Beautiful.ai', description: 'Presentation software with an AI that designs your slides for you.', url: 'https://beautiful.ai', pricing: 'Paid', category_slug: 'productivity', rating: 4.7, tags: ['Design', 'Smart Slides'] },
  { id: 'p9', view_count: 1350, use_cases: ['Writing', 'Notes'], name: 'Mem', description: 'AI-powered workspace that organizes your notes, thoughts, and ideas.', url: 'https://mem.ai', pricing: 'Freemium', category_slug: 'productivity', rating: 4.6, tags: ['Knowledge', 'Personal'] },
  { id: 'p10', view_count: 610, use_cases: ['Presentations', 'Design'], name: 'Decktopus', description: 'AI presentation builder that helps you create slides in seconds.', url: 'https://decktopus.com', pricing: 'Freemium', category_slug: 'productivity', rating: 4.5, tags: ['Quick', 'Slide Gen'] },

  // New Category: Search & Research
  { id: 's1', view_count: 2200, use_cases: ['Research', 'Search Engine'], name: 'You.com', description: 'A private search engine that summarizes the web for you.', url: 'https://you.com', pricing: 'Freemium', category_slug: 'search', rating: 4.7, tags: ['Search', 'Summarizer'] },
  { id: 's2', view_count: 1560, use_cases: ['Academic Research', 'Chat with PDF'], name: 'ChatPDF', description: 'Chat with any PDF document to summarize, understand, and extract info quickly.', url: 'https://chatpdf.com', pricing: 'Freemium', category_slug: 'search', rating: 4.8, tags: ['PDF', 'Productive'] },
  { id: 's3', view_count: 850, use_cases: ['Literature Review', 'Science'], name: 'Consensus', description: 'An AI search engine designed to extract and surface insights from scientific research.', url: 'https://consensus.app', pricing: 'Free', category_slug: 'search', rating: 4.9, tags: ['Scientific', 'Evidence'] },
  { id: 's4', view_count: 1100, use_cases: ['Research', 'Summarization'], name: 'Komo', description: 'Fast, ad-free AI search engine for deep diving into topics.', url: 'https://komo.ai', pricing: 'Free', category_slug: 'search', rating: 4.6, tags: ['Ad-free', 'Fast Search'] },
  { id: 's5', view_count: 3200, use_cases: ['Web Browsing', 'Smart Search'], name: 'Arc Search', description: 'Mobile browser that browses the web for you and builds a custom webpage with answers.', url: 'https://arc.net', pricing: 'Free', category_slug: 'search', rating: 4.9, tags: ['Browser', 'Innovative'] },

  // New Category: Marketing & SEO
  { id: 'm1', view_count: 980, use_cases: ['SEO', 'Content Creation'], name: 'Surfer SEO', description: 'AI-driven content intelligence that helps you rank higher on Google.', url: 'https://surferseo.com', pricing: 'Paid', category_slug: 'marketing', rating: 4.8, tags: ['SEO Specialist', 'Rank Higher'] },
  { id: 'm2', view_count: 1050, use_cases: ['Social Media', 'Scheduling'], name: 'Lately.ai', description: 'AI social media management and content generation platform.', url: 'https://lately.ai', pricing: 'Paid', category_slug: 'marketing', rating: 4.5, tags: ['Social Media', 'Content Gen'] },
  { id: 'm3', view_count: 650, use_cases: ['Advertising', 'Ad Copy'], name: 'AdCreative.ai', description: 'Generate conversion-focused ad creatives and social media posts.', url: 'https://adcreative.ai', pricing: 'Paid', category_slug: 'marketing', rating: 4.7, tags: ['Conversion', 'Ads'] },
  { id: 'm4', view_count: 1200, use_cases: ['Writing', 'Email Marketing'], name: 'Anyword', description: 'Data-driven AI copywriting tool that predicts performance before you publish.', url: 'https://anyword.com', pricing: 'Freemium', category_slug: 'marketing', rating: 4.8, tags: ['Data-driven', 'Copywriting'] },
  { id: 'm5', view_count: 880, use_cases: ['Email Campaigns', 'Outreach'], name: 'Lavender', description: 'In-inbox AI email assistant designed specifically for sales teams.', url: 'https://lavender.ai', pricing: 'Paid', category_slug: 'marketing', rating: 4.9, tags: ['Sales Email', 'Integration'] },

  // New Category: Customer Support
  { id: 'cs1', view_count: 1450, use_cases: ['Chatbot', 'Support Desk'], name: 'Intercom Fin', description: 'The breakthrough AI bot that resolves customer issues instantly.', url: 'https://intercom.com/fin', pricing: 'Paid', category_slug: 'customer-support', rating: 4.9, tags: ['CS Bot', 'Efficiency'] },
  { id: 'cs2', view_count: 920, use_cases: ['Automation', 'Ticketing'], name: 'Zendesk AI', description: 'Deploy AI across your customer service experience to deflect tickets.', url: 'https://zendesk.com', pricing: 'Paid', category_slug: 'customer-support', rating: 4.8, tags: ['Enterprise', 'Helpdesk'] },
  { id: 'cs3', view_count: 810, use_cases: ['Chatbots', 'Knowledge Base'], name: 'DocsBot', description: 'Create custom ChatGPT bots trained on your documentation.', url: 'https://docsbot.ai', pricing: 'Freemium', category_slug: 'customer-support', rating: 4.7, tags: ['Custom Bot', 'Docs-trained'] },
  { id: 'cs4', view_count: 560, use_cases: ['Live Chat', 'Automated Responses'], name: 'Tidio AI', description: 'Customer service platform with AI-driven chatbots for small businesses.', url: 'https://tidio.com', pricing: 'Freemium', category_slug: 'customer-support', rating: 4.6, tags: ['SMB Focus', 'Growth'] },

  // New Category: Generative 3D & Design
  { id: '3d1', view_count: 1950, use_cases: ['Web Design', 'UI/UX'], name: 'Framer AI', description: 'Generate stunning, responsive websites from text prompts instantly.', url: 'https://framer.com', pricing: 'Freemium', category_slug: 'design', rating: 4.9, tags: ['Web Gen', 'Pro Design'] },
  { id: '3d2', view_count: 820, use_cases: ['3D Modeling', 'Game Assets'], name: 'Luma AI', description: 'Create photorealistic 3D assets and environments using NeRF technology.', url: 'https://lumalabs.ai', pricing: 'Freemium', category_slug: 'design', rating: 4.8, tags: ['3D Assets', 'Realistic'] },
  { id: '3d3', view_count: 640, use_cases: ['Web Design', 'Landing Pages'], name: 'Dora AI', description: 'Design and publish stunning 3D websites with no code from simple text.', url: 'https://dora.run', pricing: 'Free', category_slug: 'design', rating: 4.7, tags: ['3D Web', 'No Code'] },
  { id: '3d4', view_count: 1100, use_cases: ['UI/UX', 'Wireframes'], name: 'Galileo AI', description: 'AI tool that creates editable UI designs from simple text descriptions.', url: 'https://usegalileo.ai', pricing: 'Freemium', category_slug: 'design', rating: 4.8, tags: ['UI Designer', 'Fast Design'] },
  { id: '3d5', view_count: 730, use_cases: ['Logos', 'Branding'], name: 'Looka', description: 'AI-powered logo maker to quickly design a beautiful brand.', url: 'https://looka.com', pricing: 'Paid', category_slug: 'design', rating: 4.7, tags: ['Logo Gen', 'Branding'] },

  // Education & Learning
  { id: 'e1', view_count: 4200, use_cases: ['Math', 'Tutoring'], name: 'Khan Academy Khanmigo', description: 'AI-powered tutoring assistant built for students and teachers by Khan Academy.', url: 'https://khanacademy.org', pricing: 'Free', category_slug: 'education', rating: 4.9, tags: ['Tutoring', 'Education'] },
  { id: 'e2', view_count: 2800, use_cases: ['Language Learning', 'Practice'], name: 'Duolingo Max', description: 'Learn a new language with AI-powered explanations and roleplay exercises.', url: 'https://duolingo.com', pricing: 'Paid', category_slug: 'education', rating: 4.8, tags: ['Language', 'Interactive'] },
  { id: 'e3', view_count: 1200, use_cases: ['Study Notes', 'Flashcards'], name: 'Quizlet AI', description: 'AI-powered studying for creating flashcards, quizzes, and summaries from your notes.', url: 'https://quizlet.com', pricing: 'Freemium', category_slug: 'education', rating: 4.7, tags: ['Flashcards', 'Study Tool'] },
  { id: 'e4', view_count: 870, use_cases: ['Essay Writing', 'Feedback'], name: 'Turnitin AI', description: 'AI writing feedback tool for students and originality checker for educators.', url: 'https://turnitin.com', pricing: 'Paid', category_slug: 'education', rating: 4.6, tags: ['Academic', 'Integrity'] },
  { id: 'e5', view_count: 1560, use_cases: ['Courses', 'Teaching'], name: 'Coursebox', description: 'AI course creator that turns documents, videos, and text into structured e-learning courses.', url: 'https://coursebox.ai', pricing: 'Freemium', category_slug: 'education', rating: 4.7, tags: ['Course Gen', 'Teaching'] },
  { id: 'e6', view_count: 990, use_cases: ['Math Solver', 'Step by Step'], name: 'Photomath', description: 'Scan and solve any math problem instantly using your phone camera.', url: 'https://photomath.com', pricing: 'Freemium', category_slug: 'education', rating: 4.8, tags: ['Math Help', 'Visual'] },

  // Finance & Business
  { id: 'f1', view_count: 1800, use_cases: ['Financial Analysis', 'Reports'], name: 'FinChat', description: 'Conversational AI for financial data, company research, and investor analysis.', url: 'https://finchat.io', pricing: 'Freemium', category_slug: 'finance', rating: 4.8, tags: ['Investing', 'Finance Chat'] },
  { id: 'f2', view_count: 1100, use_cases: ['Bookkeeping', 'Accounting'], name: 'Digits', description: 'AI-powered financial workspace offering real-time accounting and insights.', url: 'https://digits.com', pricing: 'Paid', category_slug: 'finance', rating: 4.7, tags: ['Accounting', 'Business'] },
  { id: 'f3', view_count: 1350, use_cases: ['Budgeting', 'Financial Planning'], name: 'Monarch Money', description: 'Smart personal finance app with AI insights into your spending habits.', url: 'https://monarchmoney.com', pricing: 'Paid', category_slug: 'finance', rating: 4.9, tags: ['Budgeting', 'Personal Finance'] },
  { id: 'f4', view_count: 780, use_cases: ['Contract Analysis', 'Risk'], name: 'Kira Systems', description: 'Machine learning contract review tool for due diligence and compliance.', url: 'https://kirasystems.com', pricing: 'Paid', category_slug: 'finance', rating: 4.6, tags: ['Compliance', 'Risk Analysis'] },

  // Healthcare & Wellness
  { id: 'h1', view_count: 2100, use_cases: ['Mental Health', 'Therapy'], name: 'Woebot', description: 'Mental health AI that provides evidence-based cognitive behavioral therapy.', url: 'https://woebothealth.com', pricing: 'Free', category_slug: 'healthcare', rating: 4.8, tags: ['Mental Health', 'Therapy Bot'] },
  { id: 'h2', view_count: 1650, use_cases: ['Medical Info', 'Health Q&A'], name: 'Ada Health', description: 'AI-powered app that assesses your symptoms and gives personal health guidance.', url: 'https://ada.com', pricing: 'Free', category_slug: 'healthcare', rating: 4.9, tags: ['Diagnosis', 'Health Check'] },
  { id: 'h3', view_count: 1100, use_cases: ['Fitness', 'Workout Plans'], name: 'Future', description: 'AI-assisted personal training with a dedicated human coach and smart app.', url: 'https://future.co', pricing: 'Paid', category_slug: 'healthcare', rating: 4.7, tags: ['Fitness', 'Coaching'] },
  { id: 'h4', view_count: 870, use_cases: ['Nutrition', 'Meal Planning'], name: 'Calorie.ai', description: 'AI-driven nutrition tracker that identifies food in photos and logs calories.', url: 'https://calorie.ai', pricing: 'Freemium', category_slug: 'healthcare', rating: 4.5, tags: ['Nutrition', 'Calorie Counter'] },

  // Legal
  { id: 'l1', view_count: 920, use_cases: ['Contract Review', 'Legal Docs'], name: 'Harvey AI', description: 'Generative AI built for law firms to draft, review, and analyze legal documents.', url: 'https://harvey.ai', pricing: 'Paid', category_slug: 'legal', rating: 4.9, tags: ['Legal Tech', 'Law Firm'] },
  { id: 'l2', view_count: 740, use_cases: ['Legal Research', 'Case Law'], name: 'Casetext', description: 'AI legal research platform trusted by thousands of lawyers and law firms.', url: 'https://casetext.com', pricing: 'Paid', category_slug: 'legal', rating: 4.8, tags: ['Research', 'Attorney Tool'] },
  { id: 'l3', view_count: 1100, use_cases: ['Legal Q&A', 'Document Generation'], name: 'DoNotPay', description: 'AI robot lawyer that helps you fight corporations and bureaucracy.', url: 'https://donotpay.com', pricing: 'Paid', category_slug: 'legal', rating: 4.4, tags: ['Consumer Rights', 'Robot Lawyer'] },
  { id: 'l4', view_count: 580, use_cases: ['Contract Analysis', 'Redlining'], name: 'Spellbook', description: 'AI contract drafting and review tool that integrates directly into Microsoft Word.', url: 'https://spellbook.legal', pricing: 'Paid', category_slug: 'legal', rating: 4.7, tags: ['Drafting', 'Word Plugin'] },

  // HR & Recruitment
  { id: 'hr1', view_count: 1350, use_cases: ['Resume Screening', 'Hiring'], name: 'Fetcher', description: 'AI recruiter that automates candidate sourcing and outreach.', url: 'https://fetcher.ai', pricing: 'Paid', category_slug: 'hr', rating: 4.8, tags: ['Recruiting', 'Automated Sourcing'] },
  { id: 'hr2', view_count: 980, use_cases: ['Resume Writing', 'Job Search'], name: 'Rezi', description: 'AI resume builder that writes and optimizes your CV for job applications.', url: 'https://rezi.ai', pricing: 'Freemium', category_slug: 'hr', rating: 4.7, tags: ['Resume Builder', 'Job App'] },
  { id: 'hr3', view_count: 760, use_cases: ['Interviews', 'Coaching'], name: 'Yoodli', description: 'AI speech coach that gives private, real-time feedback on communication skills.', url: 'https://yoodli.ai', pricing: 'Freemium', category_slug: 'hr', rating: 4.9, tags: ['Specch Coach', 'Interview Prep'] },
  { id: 'hr4', view_count: 1200, use_cases: ['Employee Training', 'L&D'], name: 'Learnerbly', description: 'AI-powered learning and development platform for modern workplaces.', url: 'https://learnerbly.com', pricing: 'Paid', category_slug: 'hr', rating: 4.6, tags: ['L&D', 'Workplace Learning'] },

  // Data & Analytics
  { id: 'd1', view_count: 2400, use_cases: ['Data Analysis', 'Charts'], name: 'Julius AI', description: 'Chat with your data – Julius analyzes spreadsheets and creates charts instantly.', url: 'https://julius.ai', pricing: 'Freemium', category_slug: 'data', rating: 4.9, tags: ['Data Analyst', 'Charts'] },
  { id: 'd2', view_count: 1800, use_cases: ['Business Intelligence', 'Dashboards'], name: 'Akkio', description: 'No-code AI platform for data analysis, prediction, and reporting.', url: 'https://akkio.com', pricing: 'Freemium', category_slug: 'data', rating: 4.7, tags: ['No-code AI', 'Analytics'] },
  { id: 'd3', view_count: 1100, use_cases: ['SQL', 'Database'], name: 'Text2SQL', description: 'Convert natural language questions into SQL queries using AI instantly.', url: 'https://text2sql.ai', pricing: 'Freemium', category_slug: 'data', rating: 4.6, tags: ['SQL Gen', 'Database'] },
  { id: 'd4', view_count: 3100, use_cases: ['Spreadsheet', 'Formulas'], name: 'Excel Copilot', description: 'Microsoft Copilot integrated in Excel to analyze data, write formulas, and create charts.', url: 'https://microsoft.com/excel', pricing: 'Paid', category_slug: 'data', rating: 4.8, tags: ['Excel', 'Microsoft 365'] }
];
